name: agrol
channels:
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - bzip2=1.0.8
  - ca-certificates=2022.12.7
  - cffi=1.15.1
  - cudatoolkit=11.8.0
  - cudnn=8.4.1.50
  - icu=70.1
  - ld_impl_linux-64=2.40
  - libblas=3.9.0
  - libcblas=3.9.0
  - libffi=3.4.2
  - libgcc-ng=12.2.0
  - libgfortran-ng=12.2.0
  - libgfortran5=12.2.0
  - libgomp=12.2.0
  - libhwloc=2.9.0
  - libiconv=1.17
  - liblapack=3.9.0
  - libnsl=2.0.0
  - libopenblas=0.3.21
  - libprotobuf=3.21.12
  - libsqlite=3.40.0
  - libstdcxx-ng=12.2.0
  - libuuid=2.32.1
  - libxml2=2.10.3
  - libzlib=1.2.13
  - llvm-openmp=15.0.7
  - magma=2.6.2
  - mkl=2022.2.1
  - nccl=2.14.3.1
  - ncurses=6.3
  - ninja=1.11.1
  - numpy=1.24.2
  - openssl=3.0.8
  - pip=23.0.1
  - pycparser=2.21
  - python=3.8.16
  - python_abi=3.8
  - pytorch=1.13.1
  - readline=8.1.2
  - sleef=3.5.1
  - tbb=2021.8.0
  - tk=8.6.12
  - typing_extensions=4.4.0
  - tzdata=2022g
  - wheel=0.38.4
  - xz=5.2.6
  - pip:
    - contourpy==1.0.7
    - cycler==0.11.0
    - fonttools==4.39.0
    - freetype-py==2.3.0
    - imageio==2.26.0
    - importlib-resources==5.12.0
    - kiwisolver==1.4.4
    - matplotlib==3.7.1
    - networkx==3.0
    - opencv-python==4.7.0.72
    - packaging==23.0
    - pillow==9.4.0
    - psbody-mesh==0.4
    - pyglet==2.0.5
    - pyopengl==3.1.6
    - pyparsing==3.0.9
    - pyrender==0.1.45
    - python-dateutil==2.8.2
    - pyyaml==6.0
    - pyzmq==25.0.0
    - scipy==1.10.1
    - setuptools==67.6.0
    - six==1.16.0
    - tqdm==4.65.0
    - trimesh==3.20.1
    - zipp==3.15.0
